name=Wire
version=1.0.0
author=Carlos Pereira Atencio
maintainer=Carlos Pereira Atencio <carlosperate@embeddedlog.com>
sentence=This library allows you to communicate with I2C and Two Wire Interface devices.
paragraph=Specific implementation for the BBC micro:bit, built on top of the CODAL I2C driver, provides Controller and Peripheral functionality.
category=Communication
url=https://github.com/carlosperate/ArduinoCore-microbit
architectures=microbit
includes=Wire.h
