name=SPI
version=1.0.0
author=Carlos Pereira Atencio
maintainer=Carlos Pereira Atencio <carlosperate@embeddedlog.com>
sentence=Enables the communication with devices that use the Serial Peripheral Interface (SPI) Bus.
paragraph=Specific implementation for the BBC micro:bit, built on top of the CODAL SPI driver.
category=Communication
url=https://github.com/carlosperate/ArduinoCore-microbit
architectures=microbit
includes=SPI.h
